In [1]:
# Encoding ==> Transform your categorical data into numerical data . 

# Type of Encoding ==> 

(1). Label Encoding  ==> sklearn


(2). Ordinal Encoding  ==> sklearn


(3). One-Hot Encoding  ==> sklearn 


(4). get-dummies ==> pandas 

In [2]:
# One Hot Encoding ==> 

# Categories ==> sub-categories ==> column  

In [4]:
import numpy as np 
import pandas as pd 

In [5]:
a = {
    "Animal" : ['Dog' , 'Cat' , 'Rabbit' , 'Snake' , 'Goldfish'] , 
    "Class" : ['Mammal' , 'Mammal' , 'Mammal' , 'Reptile' , 'Fish']
}

In [6]:
df = pd.DataFrame(a) 

In [7]:
df

Animal    Class
0       Dog   Mammal
1       Cat   Mammal
2    Rabbit   Mammal
3     Snake  Reptile
4  Goldfish     Fish

In [8]:
from sklearn.preprocessing import OneHotEncoder 

In [9]:
# create a one-hot encoder object 

encoder = OneHotEncoder(sparse = False) 
encoder 

OneHotEncoder(sparse=False)

In [10]:
encoder_data = encoder.fit_transform(df[['Animal' , 'Class']]) 

In [11]:
encoder_data 

array([[0., 1., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 0., 1., 0., 0.]])

In [12]:
encoded_df = pd.DataFrame(encoder_data , columns = encoder.get_feature_names_out(['Animal','Class']))

In [14]:
encoded_df

Animal_Cat  Animal_Dog  Animal_Goldfish  Animal_Rabbit  Animal_Snake  \
0         0.0         1.0              0.0            0.0           0.0   
1         1.0         0.0              0.0            0.0           0.0   
2         0.0         0.0              0.0            1.0           0.0   
3         0.0         0.0              0.0            0.0           1.0   
4         0.0         0.0              1.0            0.0           0.0   

   Class_Fish  Class_Mammal  Class_Reptile  
0         0.0           1.0            0.0  
1         0.0           1.0            0.0  
2         0.0           1.0            0.0  
3         0.0           0.0            1.0  
4         1.0           0.0            0.0

In [15]:
df

Animal    Class
0       Dog   Mammal
1       Cat   Mammal
2    Rabbit   Mammal
3     Snake  Reptile
4  Goldfish     Fish

In [16]:
# drop_first = True ==> category ==> sub-cateogory ==> first sub-category ==> drop ==> Multi-conielity 

## Example - 2

In [17]:
import numpy as np 
import pandas as pd 

In [20]:
df = pd.read_csv("C:\\Users\\saurabh\\Desktop\\pyth\\cars.csv" , usecols = ['name' , 'km_driven' , 'fuel' , 'owner' , 'selling_price'])

In [21]:
df.head()

name  selling_price  km_driven    fuel  \
0        Maruti 800 AC BSII          50000     100000  Petrol   
1  Maruti Gypsy E MG410W ST          95000     100000  Petrol   
2  Mahindra Jeep CL 500 MDI         250000      35000  Diesel   
3      Mahindra Jeep MM 540         200000      60000  Diesel   
4  Mahindra Jeep CL 500 MDI         150000     120000  Diesel   

                  owner  
0  Fourth & Above Owner  
1          Second Owner  
2          Second Owner  
3           First Owner  
4           Third Owner

In [22]:
df.isnull().sum() 

name             0
selling_price    0
km_driven        0
fuel             0
owner            0
dtype: int64

In [23]:
df['owner'].value_counts() 

First Owner             2832
Second Owner            1106
Third Owner              304
Fourth & Above Owner      81
Test Drive Car            17
Name: owner, dtype: int64

In [25]:
df['fuel'].value_counts() 

Diesel      2153
Petrol      2123
CNG           40
LPG           23
Electric       1
Name: fuel, dtype: int64

# One Hot Encoding using pandas 

In [26]:
pd.get_dummies(df , columns = ['fuel' , 'owner'])

name  selling_price  km_driven  \
0                         Maruti 800 AC BSII          50000     100000   
1                   Maruti Gypsy E MG410W ST          95000     100000   
2                   Mahindra Jeep CL 500 MDI         250000      35000   
3                       Mahindra Jeep MM 540         200000      60000   
4                   Mahindra Jeep CL 500 MDI         150000     120000   
...                                      ...            ...        ...   
4335         Hyundai Venue SX Opt Turbo BSIV        1050000       1100   
4336  Hyundai Grand i10 1.2 Kappa Magna BSIV         545000       5000   
4337      Ford Figo Aspire 1.5 TDCi Titanium         530000      45000   
4338                         Tata Harrier XE         426000       1000   
4339               Honda Amaze S Petrol BSIV         614000       1000   

      fuel_CNG  fuel_Diesel  fuel_Electric  fuel_LPG  fuel_Petrol  \
0            0            0              0         0            1   
1            0            0              0         0            1   
2            0            1              0         0            0   
3            0            1              0         0            0   
4            0            1              0         0            0   
...        ...          ...            ...       ...          ...   
4335         0            0              0         0            1   
4336         0            0              0         0            1   
4337         0            1              0         0            0   
4338         0            1              0         0            0   
4339         0            0              0         0            1   

      owner_First Owner  owner_Fourth & Above Owner  owner_Second Owner  \
0                     0                           1                   0   
1                     0                           0                   1   
2                     0                           0                   1   
3                     1                           0                   0   
4                     0                           0                   0   
...                 ...                         ...                 ...   
4335                  1                           0                   0   
4336                  1                           0                   0   
4337                  1                           0                   0   
4338                  1                           0                   0   
4339                  1                           0                   0   

      owner_Test Drive Car  owner_Third Owner  
0                        0                  0  
1                        0                  0  
2                        0                  0  
3                        0                  0  
4                        0                  1  
...                    ...                ...  
4335                     0                  0  
4336                     0                  0  
4337                     0                  0  
4338                     0                  0  
4339                     0                  0  

[4340 rows x 13 columns]

In [27]:
pd.get_dummies(df , columns = ['fuel' , 'owner'] , drop_first = True)  #it means we want to drop first sub-category in every category . 

name  selling_price  km_driven  \
0                         Maruti 800 AC BSII          50000     100000   
1                   Maruti Gypsy E MG410W ST          95000     100000   
2                   Mahindra Jeep CL 500 MDI         250000      35000   
3                       Mahindra Jeep MM 540         200000      60000   
4                   Mahindra Jeep CL 500 MDI         150000     120000   
...                                      ...            ...        ...   
4335         Hyundai Venue SX Opt Turbo BSIV        1050000       1100   
4336  Hyundai Grand i10 1.2 Kappa Magna BSIV         545000       5000   
4337      Ford Figo Aspire 1.5 TDCi Titanium         530000      45000   
4338                         Tata Harrier XE         426000       1000   
4339               Honda Amaze S Petrol BSIV         614000       1000   

      fuel_Diesel  fuel_Electric  fuel_LPG  fuel_Petrol  \
0               0              0         0            1   
1               0              0         0            1   
2               1              0         0            0   
3               1              0         0            0   
4               1              0         0            0   
...           ...            ...       ...          ...   
4335            0              0         0            1   
4336            0              0         0            1   
4337            1              0         0            0   
4338            1              0         0            0   
4339            0              0         0            1   

      owner_Fourth & Above Owner  owner_Second Owner  owner_Test Drive Car  \
0                              1                   0                     0   
1                              0                   1                     0   
2                              0                   1                     0   
3                              0                   0                     0   
4                              0                   0                     0   
...                          ...                 ...                   ...   
4335                           0                   0                     0   
4336                           0                   0                     0   
4337                           0                   0                     0   
4338                           0                   0                     0   
4339                           0                   0                     0   

      owner_Third Owner  
0                     0  
1                     0  
2                     0  
3                     0  
4                     1  
...                 ...  
4335                  0  
4336                  0  
4337                  0  
4338                  0  
4339                  0  

[4340 rows x 11 columns]

In [28]:
# log8 ==> log 2((3)) ==> 3 log2 =>3*0.1 = 0.32

# One Hot Encoding using sklearn 

In [30]:
from sklearn.model_selection import train_test_split 

In [31]:
df.head()

name  selling_price  km_driven    fuel  \
0        Maruti 800 AC BSII          50000     100000  Petrol   
1  Maruti Gypsy E MG410W ST          95000     100000  Petrol   
2  Mahindra Jeep CL 500 MDI         250000      35000  Diesel   
3      Mahindra Jeep MM 540         200000      60000  Diesel   
4  Mahindra Jeep CL 500 MDI         150000     120000  Diesel   

                  owner  
0  Fourth & Above Owner  
1          Second Owner  
2          Second Owner  
3           First Owner  
4           Third Owner

In [38]:
x_train,x_test , y_train , y_test = train_test_split(df.iloc[: , 0:5] , df.iloc[: , -3] , test_size = 0.2 , random_state  = 42)

In [39]:
x_train.head() 

name  selling_price  km_driven  \
227                           Hyundai Santro GS          80000      56580   
964   Tata Indica Vista Aura 1.3 Quadrajet BSIV         250000      80000   
2045                             Maruti SX4 VDI         340000     100000   
1025                     Maruti Swift Dzire VXi         370000      97000   
4242                 Tata Tiago 1.2 Revotron XZ         539000       2417   

        fuel         owner  
227   Petrol   First Owner  
964   Diesel  Second Owner  
2045  Diesel  Second Owner  
1025  Petrol  Second Owner  
4242  Petrol   First Owner

In [40]:
from sklearn.preprocessing import OneHotEncoder 

In [41]:
ohe = OneHotEncoder(drop = 'first' , sparse = False) 

In [42]:
ohe

OneHotEncoder(drop='first', sparse=False)

In [43]:
x_train_new = ohe.fit_transform(x_train[['fuel' , 'owner']])

In [44]:
x_train_new

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.]])

In [45]:
x_test_new = ohe.fit_transform(x_test[['fuel' , 'owner']])

In [46]:
x_test_new

array([[0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 1.],
       [0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [47]:
df

name  selling_price  km_driven  \
0                         Maruti 800 AC BSII          50000     100000   
1                   Maruti Gypsy E MG410W ST          95000     100000   
2                   Mahindra Jeep CL 500 MDI         250000      35000   
3                       Mahindra Jeep MM 540         200000      60000   
4                   Mahindra Jeep CL 500 MDI         150000     120000   
...                                      ...            ...        ...   
4335         Hyundai Venue SX Opt Turbo BSIV        1050000       1100   
4336  Hyundai Grand i10 1.2 Kappa Magna BSIV         545000       5000   
4337      Ford Figo Aspire 1.5 TDCi Titanium         530000      45000   
4338                         Tata Harrier XE         426000       1000   
4339               Honda Amaze S Petrol BSIV         614000       1000   

        fuel                 owner  
0     Petrol  Fourth & Above Owner  
1     Petrol          Second Owner  
2     Diesel          Second Owner  
3     Diesel           First Owner  
4     Diesel           Third Owner  
...      ...                   ...  
4335  Petrol           First Owner  
4336  Petrol           First Owner  
4337  Diesel           First Owner  
4338  Diesel           First Owner  
4339  Petrol           First Owner  

[4340 rows x 5 columns]

In [51]:
df[['name' , 'selling_price']]

name  selling_price
0                         Maruti 800 AC BSII          50000
1                   Maruti Gypsy E MG410W ST          95000
2                   Mahindra Jeep CL 500 MDI         250000
3                       Mahindra Jeep MM 540         200000
4                   Mahindra Jeep CL 500 MDI         150000
...                                      ...            ...
4335         Hyundai Venue SX Opt Turbo BSIV        1050000
4336  Hyundai Grand i10 1.2 Kappa Magna BSIV         545000
4337      Ford Figo Aspire 1.5 TDCi Titanium         530000
4338                         Tata Harrier XE         426000
4339               Honda Amaze S Petrol BSIV         614000

[4340 rows x 2 columns]

# Column Transformer ==> 

your total approaches ==> store in a  container ==> Column Transformer ==> less codding  ,  not time consuming , easy to find bug
 

In [52]:
import numpy as np 
import pandas as pd 

In [53]:
df = pd.read_csv("C:\\Users\\saurabh\\Desktop\\pyth\\covid_toy.csv")

In [54]:
df.head() 

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [55]:
df.isnull().sum() #this method returns total missing values in each column . 

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [56]:
from sklearn.impute import SimpleImputer  # this will fill your missing data . 

In [58]:
from sklearn.preprocessing import OrdinalEncoder , OneHotEncoder #this will encode your categorical data into numerical data . 

In [60]:
from sklearn.model_selection import train_test_split  #this will distribute your data into independent and target data . 

In [63]:
x = df.drop(columns = ['has_covid'] , axis = 1)  #Independent data 
y = df['has_covid']   #dependent data 

In [65]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2 , random_state = 42)

In [66]:
x_train.head()

age  gender  fever cough     city
55   81  Female  101.0  Mild   Mumbai
88    5  Female  100.0  Mild  Kolkata
26   19  Female  100.0  Mild  Kolkata
42   27    Male  100.0  Mild    Delhi
69   73  Female  103.0  Mild    Delhi

In [69]:
# y

In [70]:
# Manually type output 

In [93]:
# Adding simple imputer to fever column 

si = SimpleImputer() #Numerical ==> mean , median , mode  #categorical ==> Most_frequent_category
x_train_fever = si.fit_transform(x_train[['fever']])
x_test_fever = si.transform(x_test[['fever']])
x_train_fever.shape

(80, 1)

In [77]:
#Ordinal Encoder ==>  gender , cough 

oe = OrdinalEncoder(categories = [['Male' , 'Female'] , ['Mild' , 'Strong']])

x_train_gender_cough = oe.fit_transform(x_train[['gender' , 'cough']])

x_test_gender_cough = oe.fit_transform(x_test[['gender' , 'cough']])

In [91]:
x_test_gender_cough.shape

(20, 2)

In [80]:
# OneHotEncoding ==> City 

ohe = OneHotEncoder(drop = 'first' , sparse = False)  # because we don't want multi-conielity.and don't want to ovefit our data . 
x_train_city = ohe.fit_transform(x_train[['city']])

x_test_city = ohe.fit_transform(x_test[['city']])

In [89]:
x_train_city.shape

(80, 3)

In [86]:
# Extractin Age 

x_train_age = x_train.drop(columns = ['gender' , 'fever' , 'cough' , 'city']).values 

x_test_age = x_test.drop(columns = ['gender' , 'fever' , 'cough' , 'city']).values 

In [90]:
x_train_age.shape

(80, 1)

In [94]:
# Now we concatenate all the columns 

x_train_transformed = np.concatenate((x_train_age , x_train_fever , x_train_gender_cough , x_train_city) , axis = 1)

In [96]:
x_train_transformed.shape   #this is our combined data shape . 

(80, 7)

# Now we can do this using Column Transformer

In [106]:
from sklearn.compose import ColumnTransformer


transformer = ColumnTransformer(transformers = [
    ('tnf1' , SimpleImputer() , ['fever']) , 
    ('tnf2' , OrdinalEncoder(categories = [['Male' , 'Female'],['Mild' , 'Strong']]) , ['gender','cough']) , 
    ('tnf3' , OneHotEncoder(sparse = False ,drop = 'first') , ['city'])
] , remainder = 'passthrough')  #remainder = passthrough ==> it means rest all the columns remain constant . 

In [110]:
transformer.fit_transform(x_train).shape

(80, 7)

# What is Function Transformer in Machine learning ? 

# The Function transfomer is a tool in sciket learn that allows you to apply a specified function to the input data . The function transformer can be useful for performing custom transformation of input data in a machine learning pipeline . 

# Example - 1

In [111]:
import numpy as np 
from sklearn.preprocessing import FunctionTransformer 

In [112]:
#create a dataset 
x = np.array([[1,2] , [3,4]])

In [113]:
x

array([[1, 2],
       [3, 4]])

In [116]:
#define the transformation to the dataset . 
log_transform = FunctionTransformer(np.log1p)

# Apply the transformation to the dataset  
x_transformed = log_transform.transform(x) 
x_transformed 

array([[0.69314718, 1.09861229],
       [1.38629436, 1.60943791]])

# Example - 2 

In [117]:
import numpy as np 
from sklearn.preprocessing import FunctionTransformer 

In [118]:
x = np.array([[1,2] , [3,4]])
x

array([[1, 2],
       [3, 4]])

In [121]:
def my_feature_enginerring(x):    #customly created function 
    return np.hstack((x , x**2)) 

In [123]:
custom_transformer = FunctionTransformer(my_feature_enginerring)   #passour function into FunctionTransformer


In [124]:
x_transformed = custom_transformer.transform(x) 


In [125]:
x_transformed 

array([[ 1,  2,  1,  4],
       [ 3,  4,  9, 16]])