In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [2]:
!pip install numpy

     ---------------------------------------- 0.0/15.6 MB ? eta -:--:--
     ---------------------------------------- 0.1/15.6 MB 6.8 MB/s eta 0:00:03
      --------------------------------------- 0.3/15.6 MB 2.5 MB/s eta 0:00:07
     - -------------------------------------- 0.5/15.6 MB 2.6 MB/s eta 0:00:06
     - -------------------------------------- 0.6/15.6 MB 2.6 MB/s eta 0:00:06
     -- ------------------------------------- 0.8/15.6 MB 2.7 MB/s eta 0:00:06
     -- ------------------------------------- 0.9/15.6 MB 2.7 MB/s eta 0:00:06
     -- ------------------------------------- 1.0/15.6 MB 2.6 MB/s eta 0:00:06
     --- ------------------------------------ 1.2/15.6 MB 2.7 MB/s eta 0:00:06
     --- ------------------------------------ 1.4/15.6 MB 2.8 MB/s eta 0:00:06
     ---- ----------------------------------- 1.6/15.6 MB 2.8 MB/s eta 0:00:06
     ---- ----------------------------------- 1.7/15.6 MB 2.8 MB/s eta 0:00:05
     ---- ----------------------------------- 1.9/15.6 MB 2


[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

In [5]:
a=[1,2]#1d list
b=np.array(a)
b

array([1, 2])

In [6]:
a=[1,3,5],[5,9,1]#2list
b=np.array(a)
b

array([[1, 3, 5],
       [5, 9, 1]])

In [8]:
print("1",b.ndim)
print("2",b.shape)

1 2
2 (2, 3)


In [ ]:
#predefined function
a=np.zeros()

In [ ]:
a=np.ones((2,3))

In [ ]:
a=np.array

In [9]:
#random module
#1-RANDINT()=NUMBERS=(MIN,MAX, TOTAL)
#2-RAND()=0--1
#3-RANDN()

In [10]:
a=np.random.randit(1,10,3)
a

AttributeError: module 'numpy.random' has no attribute 'randit'

In [12]:
a=np.random.rand(6)

In [14]:
a=np.random.rand(3,4)
a

array([[0.96468753, 0.49096415, 0.08725078, 0.42536972],
       [0.66693922, 0.81999725, 0.9259286 , 0.49507524],
       [0.00333841, 0.3670118 , 0.04070918, 0.59524359]])

a=np.random.seed(12)
a=np.random.randint(1,10,3)
a

In [19]:
np.random.seed(12)
a=np.random.randint(1,10)
a


7

In [18]:
a=a.reshape(-1,2)
a

ValueError: cannot reshape array of size 3 into shape (2)

In [20]:
a=np.random.rand(3,4)
a

array([[0.87338715, 0.08643428, 0.7236018 , 0.35047828],
       [0.03396417, 0.29543683, 0.08252441, 0.72595416],
       [0.37283446, 0.67599758, 0.98364716, 0.48153021]])

In [21]:
#view
a=np.array([10,20,30,50,70,60])
b=a[1:4]
b

array([20, 30, 50])

In [22]:
b[:]=0
a

array([10,  0,  0,  0, 70, 60])

In [23]:
#copy
a=np.array([10,20,30,50,70,60])
b=a[1:4].copy()
b[:]=0
a

array([10, 20, 30, 50, 70, 60])

In [24]:
a=np.array([10,20,30,50,70,60])
b=a[1:4].copy()
b[:]=0
b

array([0, 0, 0])

In [27]:
#conditional selection
a=np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [28]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [29]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [30]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [31]:
c=a<10
a[c]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
c=a%2==0
a[c]

array([ 2,  4,  6,  8, 10, 12, 14])

In [34]:
#operation on array
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [35]:
a+2


array([3, 4, 5, 6])

In [36]:
a**2

array([ 1,  4,  9, 16])

In [44]:
a=a.reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [38]:
b=np.array([5,6,7,8]).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [40]:
a-b

array([[-4, -4],
       [-4, -4]])

In [41]:
b-a

array([[4, 4],
       [4, 4]])

In [42]:
a*b

array([[ 5, 12],
       [21, 32]])

In [43]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [45]:
b/a

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [46]:
#matrix multiplication
a.dot(b)

array([[19, 22],
       [43, 50]])

In [47]:
np.min(a)

1

In [49]:
np.argmin(a)#with index value and min no.

0

In [50]:
np.argmax(a)#with index value and max no.

3

In [51]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [52]:
np.cos(a)


array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [54]:
np.tan(a)

array([[ 1.55740772, -2.18503986],
       [-0.14254654,  1.15782128]])

In [55]:
#linspace()==this function returns value between given range and with same gap btw consecutive element

In [56]:
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [57]:
np.random.seed(122)
a=np.random.randint(1,21,9).reshape(3,3)
a

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [58]:
np.sum(a)

116

In [59]:
a=np.sum(a,axis=1)

array([40, 46, 30])

In [60]:
np.sum(a,axis=0)

array([36, 40, 40])

In [62]:
np.argmin(a)

6

In [63]:
np.cumsum(a)

array([ 16,  27,  40,  57,  70,  86,  89, 105, 116])

In [66]:
np.product(a)

-23252992

In [ ]:
#np.unique(arr ,return_index=True,return_counts=True)
1.the array with unique value
2.the array with respective index value
3,the array with counting frequency

In [67]:
a=np.array([10,20,30,40,10,50,10,10,50,60])
np.unique(a,return_index=True,return_counts=True)

(array([10, 20, 30, 40, 50, 60]),
 array([0, 1, 2, 3, 5, 9], dtype=int64),
 array([4, 1, 1, 1, 2, 1], dtype=int64))

In [68]:
#horizontal and vertical Stacking

In [72]:
a=np.array([10,20,30])
b=np.array([10,50,60])


In [73]:
np.hstack((a,b))

array([10, 20, 30, 10, 50, 60])

In [74]:
np.vstack((a,b))

array([[10, 20, 30],
       [10, 50, 60]])

In [77]:
#q1 write code to import numpy
import numpy as np

In [76]:
#Q2 create an array using numpy
a=np.array([10,20,30])
a


array([10, 20, 30])

In [79]:
#q3 create an array of 10 random integers
a=np.array.random.rand(11)
a


AttributeError: 'builtin_function_or_method' object has no attribute 'random'

In [80]:
a=np.random.rand(10)
a

array([0.24997735, 0.59006403, 0.89397408, 0.94819802, 0.01557357,
       0.24456027, 0.6993253 , 0.86618969, 0.95306866, 0.23666793])

In [82]:
#q4 create an array of element 10
a=np.array([10,21,10])
a


array([10, 21, 10])

In [83]:
a=[10,11,12,13,14,15,16,17,18,19,20]
b=np.array(a)
b


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [87]:
#q5 create an array which contain  value 5,10 times
a=np.ones(10)*5
a

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [95]:
a=np.array([10,20,30,40,50,60,70,80,50])
b=a.reshape(3,3)
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 50]])

In [100]:
#q7 create 2D ARRAY OF SIZE 3*3 BUT ALL ELEMENTS 0 TO 1

a=np.random.randint(0,1,9)
a
b=a.reshape(3,3)
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [101]:
#Q8 Cconcetate 2d aray horizontal and vertical
a=np.array(([10,20,30],[11,40,60]))
b=np.array(([10,50,60],[55,40,40]))
np.hstack((a,b))


array([[10, 20, 30, 10, 50, 60],
       [11, 40, 60, 55, 40, 40]])

In [102]:
a=np.array(([10,20,30],[11,40,60]))
b=np.array(([10,50,60],[55,40,40]))
np.vstack((a,b))


array([[10, 20, 30],
       [11, 40, 60],
       [10, 50, 60],
       [55, 40, 40]])

In [ ]:
i