# feature engineering

1.standarisation
2.normalisation
3.encoding
4.transformer

1.transformation={mean=0,std=1}
2.normalisation={min=0,max=1}
3.encoding
(i)data transformation

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [3]:
from sklearn.preprocessing import PowerTransformer
#generate some random data with skewed distribution
data=np.random.gamma(1,2,size=(100,1))
#instantiate a Power Transformer object
pt=PowerTransformer(method='yeo-johnson')
#fit the PowerTransformer to the data and transform it
transformed_data=pt.fit_transform(data)
#Print the original and transformed data to compare
print('Orignal data:\n',data[:5])
print('Transformed data:\n',transformed_data[:5])

Orignal data:
 [[0.42790599]
 [0.60528506]
 [0.38954345]
 [4.11572501]
 [1.1992673 ]]
Transformed data:
 [[-0.99769589]
 [-0.74134641]
 [-1.05904326]
 [ 1.24632491]
 [-0.10828994]]


In [4]:
df=pd.read_csv("C:\\Users\\User\\Desktop\\ML\\placement.csv")

In [5]:
df

cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

In [6]:
df['cgpa'] = df['cgpa'].astype(int)
df['resume_score'] = df['resume_score'].astype(int)



In [7]:
df

cgpa  resume_score  placed
0      8             6       1
1      6             5       0
2      8             8       1
3      6             7       1
4      7             7       1
..   ...           ...     ...
95     6             6       0
96     8             7       1
97     6             7       0
98     8             5       1
99     6             6       0

[100 rows x 3 columns]

In [8]:
x=df.drop(columns=['cgpa'],axis=1)
y=df['cgpa']

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [10]:
#fit and transform the data using Box-Cox method
#boxcox_transformer=PowerTransformer(method='box-cox ',standardize=True)
#x_train_bc=boxcox_transformer.fit_transform(x_train)
#x_test_bc=boxcox_transformer.transform(x_test)
#fit and transform data using yeo_jhonson method
yeojohnson_transformer=PowerTransformer(method='yeo-johnson',standardize=True)
x_train_yj=yeojohnson_transformer.fit_transform(x_train)
x_test_yj=yeojohnson_transformer.transform(x_train)

In [11]:
x_train_yj

array([[-0.55101517,  1.        ],
       [-0.55101517,  1.        ],
       [-0.55101517, -1.        ],
       [-0.55101517,  1.        ],
       [ 2.5463893 ,  1.        ],
       [-1.51880908,  1.        ],
       [-1.51880908,  1.        ],
       [ 0.45122124,  1.        ],
       [ 0.45122124,  1.        ],
       [ 0.45122124,  1.        ],
       [-0.55101517, -1.        ],
       [ 1.48457653,  1.        ],
       [-1.51880908, -1.        ],
       [ 0.45122124,  1.        ],
       [ 0.45122124,  1.        ],
       [-0.55101517,  1.        ],
       [ 1.48457653,  1.        ],
       [ 1.48457653, -1.        ],
       [ 0.45122124,  1.        ],
       [ 0.45122124,  1.        ],
       [-0.55101517, -1.        ],
       [ 0.45122124,  1.        ],
       [-0.55101517, -1.        ],
       [-0.55101517, -1.        ],
       [-0.55101517, -1.        ],
       [ 1.48457653,  1.        ],
       [-0.55101517, -1.        ],
       [-1.51880908,  1.        ],
       [ 1.48457653,

In [12]:
x_test_yj

array([[-0.55101517,  1.        ],
       [-0.55101517,  1.        ],
       [-0.55101517, -1.        ],
       [-0.55101517,  1.        ],
       [ 2.5463893 ,  1.        ],
       [-1.51880908,  1.        ],
       [-1.51880908,  1.        ],
       [ 0.45122124,  1.        ],
       [ 0.45122124,  1.        ],
       [ 0.45122124,  1.        ],
       [-0.55101517, -1.        ],
       [ 1.48457653,  1.        ],
       [-1.51880908, -1.        ],
       [ 0.45122124,  1.        ],
       [ 0.45122124,  1.        ],
       [-0.55101517,  1.        ],
       [ 1.48457653,  1.        ],
       [ 1.48457653, -1.        ],
       [ 0.45122124,  1.        ],
       [ 0.45122124,  1.        ],
       [-0.55101517, -1.        ],
       [ 0.45122124,  1.        ],
       [-0.55101517, -1.        ],
       [-0.55101517, -1.        ],
       [-0.55101517, -1.        ],
       [ 1.48457653,  1.        ],
       [-0.55101517, -1.        ],
       [-1.51880908,  1.        ],
       [ 1.48457653,

In [14]:
df1=pd.read_csv("C:\\Users\\User\\Desktop\\ML\\covid_toy.csv")

In [15]:
df1

age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [21]:
x=df1.drop(columns=['gender'],axis=1)
y=df1['gender']

In [22]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [23]:
#fit and transform the data using Box-Cox method
#boxcox_transformer=PowerTransformer(method='box-cox ',standardize=True)
#x_train_bc=boxcox_transformer.fit_transform(x_train)
#x_test_bc=boxcox_transformer.transform(x_test)
#fit and transform data using yeo_jhonson method
yeojohnson_transformer=PowerTransformer(method='yeo-johnson',standardize=True)
x_train_yj=yeojohnson_transformer.fit_transform(x_train)
x_test_yj=yeojohnson_transformer.transform(x_train)

ValueError: could not convert string to float: 'Mild'

In [24]:
df2=pd.read_csv("C:\\Users\\User\\Desktop\\ML\\tips.csv")

In [25]:
df2

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [27]:
x=df2.drop(columns=['size'],axis=1)
y=df2['size']

In [28]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [29]:
#fit and transform the data using Box-Cox method
#boxcox_transformer=PowerTransformer(method='box-cox ',standardize=True)
#x_train_bc=boxcox_transformer.fit_transform(x_train)
#x_test_bc=boxcox_transformer.transform(x_test)
#fit and transform data using yeo_jhonson method
yeojohnson_transformer=PowerTransformer(method='yeo-johnson',standardize=True)
x_train_yj=yeojohnson_transformer.fit_transform(x_train)
x_test_yj=yeojohnson_transformer.transform(x_train)

ValueError: could not convert string to float: 'Male'