In [6]:
import numpy as np

In [2]:
myarr=np.array([3,6,77],np.int8)
myarr

array([ 3,  6, 77], dtype=int8)

In [4]:
myarr[0,1]#1d list

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [9]:
myarr=np.array([[3,6,77]])
myarr

array([[ 3,  6, 77]])

In [6]:
myarr[0,1]#2d list

6

In [7]:
myarr.shape

(1, 3)

In [8]:
myarr.dtype

dtype('int8')

In [10]:
myarr[0,1]=45

In [11]:
myarr

array([[ 3, 45, 77]])

In [16]:
 zeroes=np.zeros((2,4))

In [17]:
zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
zeroes.dtype

dtype('float64')

In [19]:
zeroes.shape

(2, 4)

In [20]:
n=np.arange(15)

In [21]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
lspace=np.linspace(0,5,5)

In [24]:
lspace

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [25]:
emp=np.empty((4,6))

In [26]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        9.34609111e-307, 1.42413555e-306, 1.78019082e-306],
       [1.37959740e-306, 6.23057349e-307, 1.02360935e-306,
        1.69120416e-306, 1.78022342e-306, 6.23058028e-307],
       [1.06811422e-306, 9.45699680e-308, 1.11261027e-306,
        1.11261502e-306, 1.42410839e-306, 7.56597770e-307],
       [6.23059726e-307, 1.42419530e-306, 6.89805151e-307,
        1.78020169e-306, 1.42410974e-306, 9.34604357e-307]])

In [27]:
emp_like=np.empty_like(lspace)
emp_like

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [7]:
ide=np.identity(4)

In [8]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
ide.shape

(4, 4)

In [14]:
a=np.arange(99)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [15]:
a.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [16]:
a.reshape(33,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89],
       [90, 91, 92],
       [93, 94, 95],
       [96, 97, 98]])

In [17]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [18]:
a=a.reshape(3,33)

In [19]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [21]:
a=a.ravel()#to covert into 1 d aray
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [43]:
x=[[1,2,4],[5,6,7],[5,9,0]]

In [44]:
ar=np.array(x)
ar

array([[1, 2, 4],
       [5, 6, 7],
       [5, 9, 0]])

In [24]:
ar.sum(axis=0)#axis=0 for rows

array([14, 17, 10])

In [25]:
ar.sum(axis=1)#axis=1 for column

array([ 6, 18, 17])

In [26]:
ar.T

array([[1, 5, 8],
       [2, 6, 9],
       [3, 7, 0]])

In [27]:
ar.flat

In [28]:
for i in ar.flat:
    print(i)

1
2
3
5
6
7
8
9
0


In [29]:
ar.ndim

2

In [30]:
ar.size

9

In [31]:
ar.nbytes

36

In [33]:
one=np.array([1,5,63,4])

In [34]:
one.argmax()

2

In [35]:
one.argmin()

0

In [36]:
one.argsort()

array([0, 3, 1, 2], dtype=int64)

In [47]:
ar

array([[1, 2, 4],
       [5, 6, 7],
       [5, 9, 0]])

In [38]:
ar.argmin()

8

In [39]:
ar.argmax()

7

In [46]:
ar.argmax(axis=0)

array([1, 2, 1], dtype=int64)

In [45]:
ar.argmax(axis=1)

array([2, 2, 1], dtype=int64)

In [48]:
ar.argsort(axis=0)

array([[0, 0, 2],
       [1, 1, 0],
       [2, 2, 1]], dtype=int64)

In [50]:
ar2=np.array([[1,2,3],[5,6,7],[7,9,8]])

In [51]:
ar+ar2

array([[ 2,  4,  7],
       [10, 12, 14],
       [12, 18,  8]])

In [52]:
ar.dot(ar2)

array([[ 39,  50,  49],
       [ 84, 109, 113],
       [ 50,  64,  78]])

In [53]:
np.sqrt(ar)

array([[1.        , 1.41421356, 2.        ],
       [2.23606798, 2.44948974, 2.64575131],
       [2.23606798, 3.        , 0.        ]])

In [54]:
ar.sum()

39

In [55]:
np.where(ar>5)

(array([1, 1, 2], dtype=int64), array([1, 2, 1], dtype=int64))

In [56]:
type(np.where(ar>5))

tuple

In [58]:
np.count_nonzero(ar)

8

In [59]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [60]:
import sys

In [61]:
py_ar=[0,4,55,2]


In [62]:
np_ar=np.array(py_ar)

In [63]:
sys.getsizeof(1)*len(py_ar)

112

In [64]:
sys.getsizeof(1)

28

In [65]:
np_ar.itemsize*np_ar.size

16

In [68]:
np_ar.tolist()#make numpy array python list

[0, 4, 55, 2]